### ISSUE TITLE
Report a possible silent misconfiguration in your repository

### ISSUE THREAD

**Issue by JialuZhang** [KashifHK123/server-landing-pages#1]
In your configuration,
https://github.com/KashifHK123/server-landing-pages/blob/055b1a755a414049ab776987cbb869545a7796f5/.htaccess
```
#RewriteEngine On
#RewriteCond %{HTTPS} off
#RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
```
These three lines are silent misconfigurations. This means adding it to your system will not change any system behavior.

"RewriteEngine Off" is introduced by Apache to explicitly disable all "RewriteRule" and "RewriteCond".
That is to say, if you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then instead of commenting them all, you can explicitly set “RewriteEngine Off” to disable all "RewriteRule".

Related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```

**Comment by KashifHK123** [comment]
Thank you, Yes I know it but I keep all records just for people some time one rules work for one person, and sometimes work other rules for another person.
